@GastoResidencial_HostAddress = http://localhost:5192

### Cadastrar uma pessoa
POST {{GastoResidencial_HostAddress}}/api/pessoas
Content-Type: application/json

{
    "nome": "Mykao",
    "idade": 22
}